### ISSUE TITLE
Example Code Mistake in convert_files

### ISSUE THREAD

**Issue by David-Degnan** [wilsontom/msconverteR#3]
Hello there! 

Thanks for sharing this neat little package. I wanted to point out that in the example code section for "convert_files" there is a parameter `args` which should be `msconvert_args`

**Comment by David-Degnan** [comment]
Also, the ms_convert.Rd file indicates that `msconvert_args = c("peakPicking true 1-")` is the default, when that isn't true.

**Comment by wilsontom** [comment]
Thanks @David-Degnan for picking up on these errors. All sorted in the latest release. Thanks again !
